### ISSUE TITLE
Authentification /rest/token doesn't work

### ISSUE THREAD

**Issue by dwintergruen** [diging/giles#57]
giles askes the ID server for:
https://iXXXXX/openid/openidjwk.json

it should be:
https://iXXXXX/openid/jwk.json

Caused by: java.io.FileNotFoundException: https://XXXXXX.mpg.de/openid/openidjwk.json
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at com.nimbusds.jose.util.DefaultResourceRetriever.retrieveResource(DefaultResourceRetriever.java:95)
    at com.nimbusds.jose.jwk.source.RemoteJWKSet.updateJWKSetFromURL(RemoteJWKSet.java:139)
    ... 99 more

**Comment by jdamerow** [comment]
only partially my problem... ;) but fixed for more convenience: 1c9bb53558486be3d0fc07dff3902f7bfee237ac
